### ISSUE TITLE
Error when run "python fusion_generator.py":  AssertionError: Error: Pointcloud points must have format: 18 x n

### ISSUE THREAD

**Issue by puyoulingdi** [yuanliangxie/A-data-processing-mechanism-for-radar-and-camera-data-fusion#1]
Sincerely thank you for the code.

When I run python fusion_generator.py , the error occurs as follows. How can I solve it?
======
Loading NuScenes tables for version v1.0-mini...
23 category,
8 attribute,
4 visibility,
911 instance,
12 sensor,
120 calibrated_sensor,
31206 ego_pose,
8 log,
10 scene,
404 sample,
31206 sample_data,
18538 sample_annotation,
4 map,
Done loading in 0.4 seconds.
======
Reverse indexing ...
Done reverse indexing in 0.1 seconds.
======
{'vehicle.bus.bendy': 0, 'vehicle.bus.rigid': 0, 'vehicle.car': 1, 'vehicle.trailer': 2, 'vehicle.truck': 3}
{0: 'vehicle.bus', 1: 'vehicle.car', 2: 'vehicle.trailer', 3: 'vehicle.truck'}
Traceback (most recent call last):
  File "fusion_generator.py", line 470, in <module>
    for step, sample in enumerate(dataloader):
  File "/home/sk/.local/lib/python3.7/site-packages/torch/utils/data/dataloader.py", line 363, in __next__
    data = self._next_data()
  File "/home/sk/.local/lib/python3.7/site-packages/torch/utils/data/dataloader.py", line 403, in _next_data
    data = self._dataset_fetcher.fetch(index)  # may raise StopIteration
  File "/home/sk/.local/lib/python3.7/site-packages/torch/utils/data/_utils/fetch.py", line 44, in fetch
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "/home/sk/.local/lib/python3.7/site-packages/torch/utils/data/_utils/fetch.py", line 44, in <listcomp>
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "fusion_generator.py", line 393, in __getitem__
    image_plus, large_scale_image_plus, middle_scale_image_plus, little_scale_image_plus = self.load_image(index)
  File "fusion_generator.py", line 187, in load_image
    img_p_full, large_scale_p_full, middle_scale_p_full, little_scale_p_full = self.image_plus_creation(self.nusc, image_data=image_sample, radar_data=radar_sample, radar_cover_shape=self.radar_cover_shape,  **kwargs)
  File "/home/sk/crf-a/radar_fusion_generator/utils/fusion_projection.py", line 725, in imageplus_creation
    camera_token=camera_token, target_resolution=image_target_shape)
  File "/home/sk/crf-a/radar_fusion_generator/utils/fusion_projection.py", line 562, in map_pointcloud_to_image
    pc = RadarPointCloud(radar_points)
  File "/home/sk/.local/lib/python3.7/site-packages/nuscenes/utils/data_classes.py", line 33, in __init__
    assert points.shape[0] == self.nbr_dims(), 'Error: Pointcloud points must have format: %d x n' % self.nbr_dims()
AssertionError: Error: Pointcloud points must have format: 18 x n

**Comment by yuanliangxie** [comment]
A ha! The error occurs in the `nuscenes` package, don't worry!Because I have not upload some changed file in `nuscenes`package!

**Comment by puyoulingdi** [comment]
Oh, thanks for your reply! Could you please upload the relevant file at your convenience?

**Comment by yuanliangxie** [comment]
I have uploaded all files in the package of `nuscenes`.You can compare the error files with the repo: https://gitee.com/yuanliangxie/nuscenes.
---
If you can give us feedback on what needs to be changed, I would be very grateful.Because as time passed, I also forgot where I changed

**Comment by puyoulingdi** [comment]
I am very grateful to have you help me! Your help is greatly appreciated!

**Comment by yuanliangxie** [comment]
If you encounter problems under this project, I can help you. Thank you for your attention to my paper. It's my first meaningful repo in github!

**Comment by yuanliangxie** [comment]
你好，我的微信是: yuanliang214510890
关于这个repo的问题我可以帮助你解决



---Original---

**Comment by Tiffanydaisy** [comment]
i can't find https://gitee.com/yuanliangxie/nuscenes.
AssertionError: Error: Pointcloud points must have format: 18 x n
