### ISSUE TITLE
getitem sample

### ISSUE THREAD

**Issue by guihaik** [yuanliangxie/A-data-processing-mechanism-for-radar-and-camera-data-fusion#2]
Hello, I have some questions about the sample in getitem. May I ask large_ scale_ image_ plus, middle_ scale_ image_ plus, little_ scale_ image_ Plus these three variables are  a subset of radar data of image_ pluIs, such as image_ Plus contains all radar points, but large_ scale_ image_ Plus is only a part of radar points. If so, will there be redundancy when concatenate data.

**Comment by yuanliangxie** [comment]
Hi, the reason I choose to do this is to facilitate subset data into the network. If I just input **image_Plus** data to the network which includes three data interfaces, I can't separate **image_Plus** data in that time. Please ignore the ugly various names, hahahha.

**Comment by yuanliangxie** [comment]
just Close the Issue
