### ISSUE TITLE
how to apply it in YOLOv5?

### ISSUE THREAD

**Issue by xiaoche-24** [yuanliangxie/A-data-processing-mechanism-for-radar-and-camera-data-fusion#3]

**Comment by yuanliangxie** [comment]
Hello, I'm sorry to say that the project is only provide the preprocess of the nuscenes radar and camera data. I combinded the data preprocess method with  the yolov3 detect model in my EI paper. The yolov3 detect model I developed has been uploaded in github. You can see the [page](https://github.com/yuanliangxie/YOLOV3_SUPER/blob/master/README.en.md).  If you are familiar with the detect model  pipline, I believe you can easily apply it in yolov5. That't all info I can provid to you.
