### ISSUE TITLE
image_pure为空

### ISSUE THREAD

**Issue by bdufhus** [yuanliangxie/A-data-processing-mechanism-for-radar-and-camera-data-fusion#5]
请问在isdebug=False模式下，image_pure为空是什么原因呢？谢谢！
image_pure = cv2.cvtColor(image_pure, cv2.COLOR_RGB2BGR)
cv2.error: OpenCV(4.6.0) D:\a\opencv-python\opencv-python\opencv\modules\imgcodecs\src\loadsave.cpp:801: error: (-215:Assertion failed) !_img.empty() in function 'cv::imwrite'

**Comment by yuanliangxie** [comment]
Could you share how you solved this problem?

---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2023年1月8日(周日) 中午11:43
收件人: ***@***.***&gt;;
抄送: ***@***.***&gt;;
主题: Re: [yuanliangxie/nuscenes_data_process] image_pure为空 (Issue #5)




 
Closed #5 as completed.
